---
- name: Install basic requirements for all RHEL servers
  hosts: rhel-server
  vars:
   global_resource_path: "/home/myuser/ansible/resources"

  tasks:
    #Set authorized keys
    - name: Set authorized SSH key
      ansible.posix.authorized_key:
       user: jbrennan
       state: present
       key: "{{ lookup('file', '/home/jbrennan/ansible/sourcenix/resources/ssh/deploy-01.pub') }}"
      become: yes

    #Copy baseline auditd configuration: https://github.com/Neo23x0/auditd
    - name: Copy baseline audit.d configuration
      ansible.builtin.copy:
       src: "{{ global_resource_path }}/auditd/audit.rules"
       dest: /etc/audit/rules.d/audit.rules
       owner: root
       group: root
       mode: 0600
       backup: yes
      become: yes

    #Restart AuditD
    - name: Reload Auditd
      command: /usr/sbin/service auditd reload
      args:
       warn: false
       #https://access.redhat.com/solutions/5515011
      become: yes

    - name: Copy baseline sshd configuration
      ansible.builtin.copy:
       src: "{{ global_resource_path }}/ssh/sshd_config"
       dest: /etc/ssh/sshd_config
       owner: root
       group: root
       mode: 0600
       backup: yes
      become: yes

    #Enable automatic updates
    - name: install automatic update for rhel
      yum:
       name: dnf-automatic
       state: present
      become: yes

    - name: Enable a timer for dnf-automatic-install service
      ansible.builtin.systemd:
       name: dnf-automatic-install.timer
       state: restarted
       enabled: yes
       daemon_reload: yes
      become: yes

    #Install standard utilities, removed for RHEL9
    - name: install fail2ban
      yum:
       name: fail2ban
       state: present
       update_cache: no
      become: yes

    - name: Enable fail2ban.service
      ansible.builtin.systemd:
       name: fail2ban.service
       enabled: yes
      become: yes



